#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parsePGN } from "../src/lib/pgn";
import type { ParsedMove } from "../src/lib/types";

type Opening = {
  eco: string;
  name: string;
  pgn: string;
  parsed_pgn: ParsedMove[];
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function parseTsv(content: string) {
  const lines = content.split(/\r?\n/).filter(Boolean);
  if (lines.length === 0) return [];
  const headers = lines[0].split("\t");
  const ecoIdx = headers.indexOf("eco");
  const nameIdx = headers.indexOf("name");
  const pgnIdx = headers.indexOf("pgn");

  const rows = [] as Array<{ eco: string; name: string; pgn: string }>;
  for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split("\t");
    const eco = cols[ecoIdx] || "";
    const name = cols[nameIdx] || "";
    const pgn = cols[pgnIdx] || "";
    if (eco && name && pgn) {
      rows.push({ eco, name, pgn });
    }
  }
  return rows;
}

function run() {
  const tsvFiles = fs
    .readdirSync(__dirname)
    .filter((file) => file.endsWith(".tsv"))
    .map((file) => path.join(__dirname, file));

  const openings: Opening[] = [];
  for (const file of tsvFiles) {
    const content = fs.readFileSync(file, "utf8");
    const rows = parseTsv(content);
    for (const row of rows) {
      openings.push({
        eco: row.eco,
        name: row.name,
        pgn: row.pgn,
        parsed_pgn: parsePGN(row.pgn),
      });
    }
  }

  const output = `// Generated by dat/gen.ts. Do not edit by hand.\n` +
    `import type { ParsedMove } from "./types";\n\n` +
    `export type Opening = {\n` +
    `  eco: string;\n` +
    `  name: string;\n` +
    `  pgn: string;\n` +
    `  parsed_pgn: ParsedMove[];\n` +
    `};\n\n` +
    `export const openings: Opening[] = ${JSON.stringify(openings, null, 2)};\n`;

  const outPath = path.join(__dirname, "..", "src", "lib", "openings.ts");
  fs.writeFileSync(outPath, output, "utf8");

  console.log(`Generated ${openings.length} openings -> ${outPath}`);
}

run();
